<a href="https://colab.research.google.com/github/SHIVRAJSHINDE/Colab01/blob/main/Word2VecAssignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!gdown --id 1vZ4S0dtiUk5LqeeccqWs9IAAG8qH1GWv


/usr/local/lib/python3.10/dist-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From (original): https://drive.google.com/uc?id=1vZ4S0dtiUk5LqeeccqWs9IAAG8qH1GWv
From (redirected): https://drive.google.com/uc?id=1vZ4S0dtiUk5LqeeccqWs9IAAG8qH1GWv&confirm=t&uuid=8227daca-622d-46be-8d80-bb9e3e7c4308
To: /content/News_Category_Dataset.zip
100% 27.8M/27.8M [00:01<00:00, 22.6MB/s]


In [4]:
import pandas as pd
news_df = pd.read_json("/content/News_Category_Dataset.zip",lines=True)
news_df.head(3)



link  \
0  https://www.huffpost.com/entry/covid-boosters-...   
1  https://www.huffpost.com/entry/american-airlin...   
2  https://www.huffpost.com/entry/funniest-tweets...   

                                            headline   category  \
0  Over 4 Million Americans Roll Up Sleeves For O...  U.S. NEWS   
1  American Airlines Flyer Charged, Banned For Li...  U.S. NEWS   
2  23 Of The Funniest Tweets About Cats And Dogs ...     COMEDY   

                                   short_description               authors  \
0  Health experts said it is too early to predict...  Carla K. Johnson, AP   
1  He was subdued by passengers and crew when he ...        Mary Papenfuss   
2  "Until you have a dog you don't understand wha...         Elyse Wanshel   

        date  
0 2022-09-23  
1 2022-09-23  
2 2022-09-23

In [6]:
news_df = news_df[['headline','category']]
news_df


headline   category
0       Over 4 Million Americans Roll Up Sleeves For O...  U.S. NEWS
1       American Airlines Flyer Charged, Banned For Li...  U.S. NEWS
2       23 Of The Funniest Tweets About Cats And Dogs ...     COMEDY
3       The Funniest Tweets From Parents This Week (Se...  PARENTING
4       Woman Who Called Cops On Black Bird-Watcher Lo...  U.S. NEWS
...                                                   ...        ...
209522  RIM CEO Thorsten Heins' 'Significant' Plans Fo...       TECH
209523  Maria Sharapova Stunned By Victoria Azarenka I...     SPORTS
209524  Giants Over Patriots, Jets Over Colts Among  M...     SPORTS
209525  Aldon Smith Arrested: 49ers Linebacker Busted ...     SPORTS
209526  Dwight Howard Rips Teammates After Magic Loss ...     SPORTS

[209527 rows x 2 columns]

In [7]:
news_df.isnull().sum()


headline    0
category    0
dtype: int64

In [8]:
news_df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209527 entries, 0 to 209526
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype 
---  ------    --------------   ----- 
 0   headline  209527 non-null  object
 1   category  209527 non-null  object
dtypes: object(2)
memory usage: 3.2+ MB


In [11]:
news_df['headline'] = news_df['headline'].astype(str)
news_df


headline   category
0       Over 4 Million Americans Roll Up Sleeves For O...  U.S. NEWS
1       American Airlines Flyer Charged, Banned For Li...  U.S. NEWS
2       23 Of The Funniest Tweets About Cats And Dogs ...     COMEDY
3       The Funniest Tweets From Parents This Week (Se...  PARENTING
4       Woman Who Called Cops On Black Bird-Watcher Lo...  U.S. NEWS
...                                                   ...        ...
209522  RIM CEO Thorsten Heins' 'Significant' Plans Fo...       TECH
209523  Maria Sharapova Stunned By Victoria Azarenka I...     SPORTS
209524  Giants Over Patriots, Jets Over Colts Among  M...     SPORTS
209525  Aldon Smith Arrested: 49ers Linebacker Busted ...     SPORTS
209526  Dwight Howard Rips Teammates After Magic Loss ...     SPORTS

[209527 rows x 2 columns]

In [12]:
news_df['category'].value_counts()


category
POLITICS          35602
WELLNESS          17945
ENTERTAINMENT     17362
TRAVEL             9900
STYLE & BEAUTY     9814
PARENTING          8791
HEALTHY LIVING     6694
QUEER VOICES       6347
FOOD & DRINK       6340
BUSINESS           5992
COMEDY             5400
SPORTS             5077
BLACK VOICES       4583
HOME & LIVING      4320
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3653
WOMEN              3572
CRIME              3562
IMPACT             3484
DIVORCE            3426
WORLD NEWS         3299
MEDIA              2944
WEIRD NEWS         2777
GREEN              2622
WORLDPOST          2579
RELIGION           2577
STYLE              2254
SCIENCE            2206
TECH               2104
TASTE              2096
MONEY              1756
ARTS               1509
ENVIRONMENT        1444
FIFTY              1401
GOOD NEWS          1398
U.S. NEWS          1377
ARTS & CULTURE     1339
COLLEGE            1144
LATINO VOICES      1130
CULTURE & ARTS     1074
EDUCATION          1014
Name: count, dtype: int64

In [20]:
top_categories = ['POLITICS','ENTERTAINMENT','BUSINESS','SPORTS']
top_categories
news_df = news_df[news_df['category'].isin(top_categories)]
news_df['category'].value_counts()



category
POLITICS         35602
ENTERTAINMENT    17362
BUSINESS          5992
SPORTS            5077
Name: count, dtype: int64

In [21]:
news_df


headline       category
17      Maury Wills, Base-Stealing Shortstop For Dodge...         SPORTS
20      Golden Globes Returning To NBC In January Afte...  ENTERTAINMENT
21      Biden Says U.S. Forces Would Defend Taiwan If ...       POLITICS
24      ‘Beautiful And Sad At The Same Time’: Ukrainia...       POLITICS
26      Las Vegas Aces Win First WNBA Title, Chelsea G...         SPORTS
...                                                   ...            ...
209513  'Girl With the Dragon Tattoo' India Release Ca...  ENTERTAINMENT
209523  Maria Sharapova Stunned By Victoria Azarenka I...         SPORTS
209524  Giants Over Patriots, Jets Over Colts Among  M...         SPORTS
209525  Aldon Smith Arrested: 49ers Linebacker Busted ...         SPORTS
209526  Dwight Howard Rips Teammates After Magic Loss ...         SPORTS

[64033 rows x 2 columns]

In [24]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split


In [26]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(news_df['headline'])
sequences = tokenizer.texts_to_sequences(news_df['headline'])
sequences


[[22359, 22360, 2523, 5541, 16577, 7, 3550, 468, 13, 7111],
 [591, 1065, 2722, 2, 2025, 3, 1993, 20, 96, 99, 1128],
 [169, 17, 39, 38, 2997, 113, 1177, 6642, 89, 809, 13507],
 [16578,
  8,
  1726,
  13,
  1,
  651,
  11555,
  6643,
  4785,
  730,
  264,
  9,
  5,
  4578,
  3154,
  26,
  96],
 [1547, 956, 10163, 138, 49, 5252, 1066, 1437, 3551, 1456, 6219],
 [167, 2595, 17, 46, 22361, 11, 4786, 205, 16579, 515],
 [169, 17, 13508, 149, 697, 13509, 13510, 7, 3255, 303],
 [931, 16580, 7112, 3155, 22362, 6644, 565, 5542, 41, 4579, 262],
 [57, 2, 209, 13511, 53, 11556, 7113, 715, 501, 3448, 3, 1, 68],
 [65, 16581, 4, 1, 13512, 2, 642, 9, 2469, 219, 96],
 [456, 7711, 22363, 11, 239, 5006, 3799, 102],
 [5007, 1316, 5008, 5, 1053, 284, 156, 65, 297, 9163, 1921],
 [225, 2424, 219, 2112, 67, 24, 5, 22364],
 [22365, 1644, 13513, 8388, 7, 1922, 9, 22366, 6220],
 [4080, 1266, 4580, 643, 321, 2, 37, 272, 792, 243, 3, 1, 16582],
 [1790, 364, 13514, 10164, 2, 5, 412, 922, 22, 147, 2723, 756, 2, 1500],


In [27]:
max_length = 100
X = pad_sequences(sequences=sequences,maxlen=max_length)
X


array([[    0,     0,     0, ...,   468,    13,  7111],
       [    0,     0,     0, ...,    96,    99,  1128],
       [    0,     0,     0, ...,    89,   809, 13507],
       ...,
       [    0,     0,     0, ...,    55,    80,  1522],
       [    0,     0,     0, ..., 10230,     7,  5265],
       [    0,     0,     0, ...,  1039,     2, 13973]], dtype=int32)

In [29]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(news_df['category'])
y


array([3, 1, 2, ..., 3, 3, 3])

In [30]:
from sklearn.model_selection import train_test_split

# Assume X and y are your features and labels
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train


array([[    0,     0,     0, ...,  3102,    36,   500],
       [    0,     0,     0, ...,   235,    13,  2540],
       [    0,     0,     0, ...,   728,   136,   155],
       ...,
       [    0,     0,     0, ...,   185,  3008,   561],
       [    0,     0,     0, ...,     7,     6,   221],
       [    0,     0,     0, ..., 11538,   475,   563]], dtype=int32)

In [32]:
vocab_size = len(tokenizer.word_index)+1
vocab_size
len_ofClass = len(label_encoder.classes_)
len_ofClass

41828

In [34]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GlobalAveragePooling1D,Dense


In [40]:
model= Sequential()
model.add(Embedding(vocab_size,output_dim=32,input_length=max_length))
model.add(GlobalAveragePooling1D())
model.add(Dense(64,activation='relu'))
model.add(Dense(len_ofClass,activation='softmax'))
model.summary()


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ global_average_pooling1d_2           │ ?                           │     0 (unbuilt) │
│ (GlobalAveragePooling1D)             │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [43]:

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])


In [44]:
model.summary()


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ global_average_pooling1d_2           │ ?                           │     0 (unbuilt) │
│ (GlobalAveragePooling1D)             │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [58]:
model.fit(X_train,y_train,epochs=8,batch_size=128,validation_data=(X_test,y_test))


Epoch 1/8
401/401 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.8614 - loss: 0.3997 - val_accuracy: 0.8354 - val_loss: 0.4515
Epoch 2/8
401/401 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.8809 - loss: 0.3496 - val_accuracy: 0.8281 - val_loss: 0.4806
Epoch 3/8
401/401 ━━━━━━━━━━━━━━━━━━━━ 10s 13ms/step - accuracy: 0.8960 - loss: 0.3199 - val_accuracy: 0.8571 - val_loss: 0.4168
Epoch 4/8
401/401 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9084 - loss: 0.2843 - val_accuracy: 0.8413 - val_loss: 0.4545
Epoch 5/8
401/401 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - accuracy: 0.9125 - loss: 0.2688 - val_accuracy: 0.8563 - val_loss: 0.4071
Epoch 6/8
401/401 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9276 - loss: 0.2318 - val_accuracy: 0.8758 - val_loss: 0.3728
Epoch 7/8
401/401 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - accuracy: 0.9290 - loss: 0.2240 - val_accuracy: 0.8598 - val_loss: 0.4233
Epoch 8/8
401/401 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9376 - loss: 0.2011 - val_accuracy: 

In [59]:
model.summary()


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ (None, 100, 32)             │       1,338,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ global_average_pooling1d_2           │ (None, 32)                  │               0 │
│ (GlobalAveragePooling1D)             │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 64)                  │           2,112 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 4)                   │             260 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 4,022,606 (15.35 MB)

 Trainable params: 1,340,868 (5.12 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2,681,738 (10.23 MB)

In [60]:
model.save_weights('news.weights.h5')


In [61]:
import numpy as np
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

y_pred = np.argmax(model.predict(X_test),axis=1)
y_pred


401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step


array([1, 2, 2, ..., 1, 2, 1])

In [62]:
cm = confusion_matrix(y_test,y_pred)
cm


array([[ 811,   71,  362,   47],
       [  42, 3135,  245,   48],
       [ 170,  246, 6599,   25],
       [  69,  132,   62,  743]])

In [63]:
accuracy_score(y_test,y_pred)


0.8813929882095729

In [64]:
report = classification_report(y_test,y_pred,target_names=label_encoder.classes_)
print(report)


               precision    recall  f1-score   support

     BUSINESS       0.74      0.63      0.68      1291
ENTERTAINMENT       0.87      0.90      0.89      3470
     POLITICS       0.91      0.94      0.92      7040
       SPORTS       0.86      0.74      0.80      1006

     accuracy                           0.88     12807
    macro avg       0.85      0.80      0.82     12807
 weighted avg       0.88      0.88      0.88     12807

